### ISSUE TITLE
什么时候公布代码呀？

### ISSUE THREAD

**Issue by Bigelephant0** [MIV-XJTU/ARTrack#1]

**Comment by Bigelephant0** [comment]
毕竟23年的新论文，再等等吧。

**Comment by AlexDotHam** [comment]
Coming 已经 Soon 了   QAQ

**Comment by suyzhi** [comment]
Looking forward to opening a source.

**Comment by AlexDotHam** [comment]
I will open the test code and model(including checkpoints) in the next two weeks because I need to train our model (I lost the original checkpoint, but the accuracy will be accelerated), after that i will open the training code soon
