### ISSUE TITLE
Test on my own video sequence

### ISSUE THREAD

**Issue by klein0809** [MIV-XJTU/ARTrack#18]
Thank you for your amazing work!
Is there any interface to test on my own video sequence? Appreciate!

**Comment by AlexDotHam** [comment]
I'm really sorry, I currently don't have any interfaces available. However, our model is re-implemented based on the Pytracking codebase. I believe Pytracking has interfaces like this, you can check it out yourself.

**Comment by klein0809** [comment]
> I'm really sorry, I currently don't have any interfaces available. However, our model is re-implemented based on the Pytracking codebase. I believe Pytracking has interfaces like this, you can check it out yourself.

Hello, I have just tested on my own data! Just call the method "run_video" of class Tracker ! Nice work!

**Comment by G1tQuality** [comment]
> > I'm really sorry, I currently don't have any interfaces available. However, our model is re-implemented based on the Pytracking codebase. I believe Pytracking has interfaces like this, you can check it out yourself.
> 
> Hello, I have just tested on my own data! Just call the method "run_video" of class Tracker ! Nice work!

@klein0809  Could you please give more advice about testing on my own data? Thank you very much!
