### ISSUE TITLE
model open issue

### ISSUE THREAD

**Issue by June-hui** [MIV-XJTU/ARTrack#20]
thank you for your awesome jobs, can u open the artrack 384 and  artrack-L 384 model? thank you so much.

**Comment by AlexDotHam** [comment]
I'm very sorry, since I don't have enough A6000 to use, I may not be able to retrain a checkpoint suitable for this code. If you have enough resources, please contact me by email and I will send you the corresponding yaml file.

**Comment by June-hui** [comment]
ok,thank,How much video memory does artrack384 need?

**Comment by AlexDotHam** [comment]
Both base_384 and large_384 require GPUs with over 48GB of VRAM for training. According to our experimental observations, the larger the VRAM, i.e. the longer the frame length in the second stage of training, the better the experimental results will be. Therefore, if you have devices with larger VRAM, you can achieve higher accuracy.

**Comment by hmbb123** [comment]
Can I ask if you have reproduced the accuracy of ARTrack-384? Can you provide me with the checkpoints you were able to train, thank you very much for your help!
