### ISSUE TITLE
gpu显存占用的问题

### ISSUE THREAD

**Issue by xiaohaiLi12** [MIV-XJTU/ARTrack#23]
您好！请问方便告知一下256版本bs=8的情况下显存的占用是多少吗

**Comment by xiaohaiLi12** [comment]
我直接开始跑第二阶段训练的时候bs=1的情况下11G的显存剩余，还会提示我显存爆了

**Comment by AlexDotHam** [comment]
在我的设置下为24G，显存过高是因为BS实际不影响二阶段的显存，二阶段的显存是由采样的视频内帧数决定的。
想象一种情况，采样一段视频，并实现帧内自回归，实际上的计算图仅仅取决于视频内的帧长度，这是因为不同视频实际可以公用同一个计算图，因此BS在这里不改变显存占用，而采样帧的数量影响了真正的显存占用，我建议您可以适当减小采样帧数量，但是我们的试验结果认为，越多的采样帧可以获得更高的精度。

**Comment by xiaohaiLi12** [comment]
好的，谢谢您的答复&nbsp;


1209888576
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yifan ***@***.***&gt;; 
发送时间: 2023年8月22日(星期二) 凌晨1:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MIV-XJTU/ARTrack] gpu显存占用的问题 (Issue #23)





 
在我的设置下为24G，显存过高是因为BS实际不影响二阶段的显存，二阶段的显存是由采样的视频内帧数决定的。
 想象一种情况，采样一段视频，并实现帧内自回归，实际上的计算图仅仅取决于视频内的帧长度，这是因为不同视频实际可以公用同一个计算图，因此BS在这里不改变显存占用，而采样帧的数量影响了真正的显存占用，我建议您可以适当减小采样帧数量，但是我们的试验结果认为，越多的采样帧可以获得更高的精度。
