### ISSUE TITLE
Equiment and time

### ISSUE THREAD

**Issue by kun-dragon** [MIV-XJTU/ARTrack#25]
Great jobs!
What GPUs are used and how long to train?

**Comment by AlexDotHam** [comment]
We use 4x3090 to train the model. For the got-only training, in the first stage, it's about 10 hours, in the second stage, it depends on your CPU speed.

**Comment by AlexDotHam** [comment]
In ViT-Large model, we use 4xA6000 to train the model. For the got-only training, in the first stage, it's about 32 hours, in the second stage, it's about 79 hours.
