### ISSUE TITLE
About training ARTrack_seq

### ISSUE THREAD

**Issue by kyuewang17** [MIV-XJTU/ARTrack#27]
Hi, thanks for a great work!

I was wondering how much GPU memory (in GBs) would it cost to train ARTrack_seq model by using batch size of "1".

**Comment by AlexDotHam** [comment]
it may be the same as batch_size=8 or more because the computer graph is based on the search frames in video clips. 
How many frames determines how much GPU memory you use, so you can employ a lower search number to decrease that.
