### ISSUE TITLE
推理速度

### ISSUE THREAD

**Issue by June-hui** [MIV-XJTU/ARTrack#28]
作者您好，请问一下您的推理速度是怎么得到的 ？还有您的代码是默认26fps版本还是45fps版本或者可以切换？(我在测试got10k数据集时的平均帧率得到是26fps左右)，期待您的回复谢谢！

**Comment by AlexDotHam** [comment]
这次开源的代码中并没有提供45FPS的版本，您可以自行更改decoder中的执行逻辑（如论文中展示的那样）。我们的推理速度是使用单卡3090的情况下直接通过对1000帧长的视频连续推理得到的平均值，其推理速度接近我们在GOT-10k推理时得到的速度，如果您仅使用单帧推理，我们相信速度会更上一层楼。

**Comment by June-hui** [comment]
好的，谢谢你的回复！请问您有计划开源45fps的版本吗？

**Comment by AlexDotHam** [comment]
我暂时没有时间开源这个版本，我认为只要按照论文里的范式，改一下Decoder的Forward结构即可，训练的config文件相同。

**Comment by June-hui** [comment]
好的，谢谢你！
