### ISSUE TITLE
Performance on GOK-10k

### ISSUE THREAD

**Issue by qkdkralsgh** [MIV-XJTU/ARTrack#30]
Hello, first of all thank you for the good work.

I have one question: Is the performance of the ARTrack_L384 model on the got10k dataset the performance learned on the full dataset? (AO : 78.5%)

**Comment by AlexDotHam** [comment]
No, the GOT-10k performance we provide that only trained on GOT-10k full train sets. You can see the leaderboard of GOT-10k, we trained full datasets including LaSOT, TrackingNet, COCO2017, and GOT-10k_vottrain provide higher performance (AO: 79.6%).
I can provide other full datasets performance, ARTrack_256 about 75.5% on AO, ARTrack_384 about 77.2% on AO.

**Comment by qkdkralsgh** [comment]
Thank you for answer. So, where is the yaml file when training a large model with only got10k dataset?

**Comment by AlexDotHam** [comment]
You can follow the large model yaml and set the training epoch same as base_256_got, and batch_size same as large mode's yaml. Others hyper-parameter is same as large model.

**Comment by qkdkralsgh** [comment]
Thank you very much!
