### ISSUE TITLE
I wanna reproduce ARTrack-L-384

### ISSUE THREAD

**Issue by XJLeoYu** [MIV-XJTU/ARTrack#31]
but seems that the files you provided didn't match,it report bug:
dim 1024 should be divided by num_heads 12

**Comment by AlexDotHam** [comment]
Sorry, the num_heads should be 16, i will change that soon.

**Comment by XJLeoYu** [comment]
When I changed the num_heads back to 16,it's still bugy

**Comment by XJLeoYu** [comment]
I was just planing to inference not traning,not pretty sure how to find you mail or wechat account on github

**Comment by AlexDotHam** [comment]
You can mail me yfbai@stu.xjtu.edu.cn

**Comment by Jasper0420** [comment]
您好，我在使用384给出的权重推理时出现以下shape不匹配的问题？ ```
size mismatch for pix_head.decoder.layers.3.multihead_attn.in_proj_bias: copying a param with shape torch.Size([3072]) from checkpoint, the shape in current model is torch.Size([2304]).
        size mismatch for pix_head.decoder.layers.3.multihead_attn.out_proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for pix_head.decoder.layers.3.multihead_attn.out_proj.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pix_head.decoder.layers.3.norm_3.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pix_head.decoder.layers.3.norm_3.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for pix_head.decoder.layers.3.mlpz.fc1.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for pix_head.decoder.layers.3.mlpz.fc1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for pix_head.decoder.layers.3.mlpz.fc2.weight: copying a param with shape torch.Size([1024, 4096]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
```
请问应该如何修改yaml文件或者其他配置吗？

**Comment by AlexDotHam** [comment]
It seems like you use the ARTrack-L-384 model checkpoints with a ARTrack-B-384 yaml, you can check the yaml you use to match the checkpoints.

**Comment by Jasper0420** [comment]
Thanks!
Good luck!
