### ISSUE TITLE
Checkpoints of artrack384, artrack-l384

### ISSUE THREAD

**Issue by XiaokunFeng** [MIV-XJTU/ARTrack#33]
Could you please provide the checkpoints of artrack384, artrack-l384?
Thanks a lot !!

**Comment by AlexDotHam** [comment]
So sorry for that i can not provide the checkpoints you mentioned above, the main problem is i don't have the right to get the checkpoint in company, so i can only trained the code on my server, but i solely have 8x3090.  You can try to reproduce ARTrack-L384, In my experiments, the training process is very rough and easier to reproduce.
