### ISSUE TITLE
Implementation method of heatmap visualization (as shown in Figure 6 of the ARTrack paper).

### ISSUE THREAD

**Issue by XiaokunFeng** [MIV-XJTU/ARTrack#34]
Thanks for your art and solid work. I would like to inquire about how to implement heat map visualization for this autoregressive-based tracker, as shown in Figure 6 of the ARTrack paper. I would greatly appreciate it if you could provide the relevant source code.
![image](https://github.com/MIV-XJTU/ARTrack/assets/103614531/7eb6a576-f2b3-4321-bf3f-48480271100b)

**Comment by AlexDotHam** [comment]
So sorry for that i lost that code, but you can make it easy. When u inference in a sequence, you can save the cross-attention map of respective coordinate token and the search region, after that you can use the visulization tools such as: https://github.com/rentainhe/visualization/tree/master. I think you can contribute your tools in 2 hours.

**Comment by XiaokunFeng** [comment]
Thank you for your reply.I have made it under your guidance !!
