### ISSUE TITLE
Can ARTrack predict when no object is present?

### ISSUE THREAD

**Issue by psandovalsegura** [MIV-XJTU/ARTrack#40]
I have video sequences where objects come in and out of frame. If I include every frame of the video in the `Sequence` object, ARTrack predicts a bounding box for every frame. Can ARTrack predict when the template object is not present? How would I implement that?

**Comment by AlexDotHam** [comment]
In ARTrackV2, there is a solution named confidence token. But in ARTrack, i think one effective way is to average the probability of four coordinates we predict in current frame. After that, you can set a overlap to filterate low score predict and consider it as that the target exit the field of vision.
