### ISSUE TITLE
pretrained-weights

### ISSUE THREAD

**Issue by Mingxiao-Li** [MIV-XJTU/ARTrack#42]
hello, this is a very nice work. I am wondering where I can download the pretrained weights ? I could not find ckpt in the provided gdrive link.

**Comment by ARTrackV2** [comment]
In gdrive link's Checkpoint/ARTrack_seq_base_256_full/ you will find the pth file, the specific link is [https://drive.google.com/drive/folders/1w93eQ4stfwdHrmWWnABXQrSsX7phtAd0](url)
