### ISSUE TITLE
无助的小白

### ISSUE THREAD

**Issue by yefeng23323** [MIV-XJTU/ARTrack#44]
首先恭喜大佬，我是最近刚接触单目标跟踪的白。有些问题想请教一下：
1.我查了一些关于单目标跟踪的数据集，有Lasot，Got10k，trackingnet，otb，uav123，vot等等。然后看到有些人说otb，uav123数据集只作测试用不会用作训练，我查了一些还是不确定具体的规则，所以请教一下作者大大这方面的知识。
2.看了一些关于单目标跟踪的代码，那个数据准备部分的示例（你放了lasot，got10k，coco，trackingnet），这是指多个不同的数据集一起训练吗？（如果一起训练的话，测试指标是怎么算的呢？）
3.还有就是你的配置文件，比如artrack_256_full.yaml 与artrack_256_got.yaml, 这两个区别是指第一个用3个数据集一起训练，第二只用got训练吗？
4.你这里的配置文件，artrack与artrack_seq的区别是第一个是当（N=0，论文中讲到的N）

纯小白，刚接触有点找不到方向入门，希望作者大大指导一下（不胜感激）。

**Comment by AlexDotHam** [comment]
1、通常来说LaSOT TrackingNet GOT10k 和 coco作为训练集，在推理时不使用。在评测GOT-10k时通常使用GOT10k全量的训练集进行训练而不使用其他数据集，在推理剩下的数据集时使用votsplit的GOT10k、TrackingNet、LaSOT、COCO进行训练。
2、多个数据集共同训练，分别在各自的测试集进行测试。
3、是的，这是两种评价规则，如1中回答，在评价GOT10k时，仅能在GOT上训练。
4、你的理解是正确的，同时artrack和artrack_seq是分别进行的两阶段的训练，一阶段为N=0的采样帧对匹配，二阶段为采样连续视频帧进行训练。

**Comment by yefeng23323** [comment]
非常感谢作者大大的回复，如果可以的话可以加个联系方式吗？（想向请教一下这方面研究的经验和方法，如果可以的话可以将联系方式发我的邮箱，然后我添加你。）

**Comment by AlexDotHam** [comment]
您可以给我发邮件哈，这里不方便放个人联系方式:yfbai@stu.xjtu.edu.cn
