### ISSUE TITLE
Is that any c++ implementation ? 

### ISSUE THREAD

**Issue by SJavad** [MIV-XJTU/ARTrack#46]
Hi
I want to run this tracker on Nvidia Jetson and use C++ to improve performance.
how can I use this Tracker in C++?
is there a way to convert this model to tensorRT and use it in C++?

**Comment by ARTrackV2** [comment]
I'm afraid I'm not too familiar with deep learning inference frameworks, so I might not be the best person to answer your question. I haven't had the chance to work directly with inference frameworks like TensorRT either. However, if you have any ideas for optimization, I'd find that really intriguing and worth exploring!

**Comment by SJavad** [comment]
> I'm afraid I'm not too familiar with deep learning inference frameworks, so I might not be the best person to answer your question. I haven't had the chance to work directly with inference frameworks like TensorRT either. However, if you have any ideas for optimization, I'd find that really intriguing and worth exploring!

Hi thanks for your response ☺️
Yes your method and paper is very strong for tracking (in the laboratory and science) but when you want to use this method in real and industrial environment your method will not succeed because of time consumption and requires hardware and environments... 
That's why I trying to find a way that implementing this method with c++. 
TensorRT is for embedded systems like Jetson.
I hope you are looking for a way to implement this method on C++
I suggest that use libtorch library based on torch.

**Comment by AlexDotHam** [comment]
I am also looking for a job recently, and I may not have enough time to do the aforementioned work. However, when I have free time, I will consider this matter. Thank you for your suggestion

**Comment by iMaTzzz** [comment]
Hi @SJavad !
I'm not sure if you are still looking for a way to use this model in C++ but you may want to look into onnx and onnx runtime. If you manage to export the model to the onnx format, you should be able to run it from anywhere such as a C++ environment.
