### ISSUE TITLE
Eliminate intra-frame autoregression

### ISSUE THREAD

**Issue by self-memory** [MIV-XJTU/ARTrack#47]
作者您好，您在ARTrack V2中提到【Eliminate intra-frame autoregression】，您的意思是在推理时摒弃了ARTrack解码器循环四次的帧间自回归策略吗？想请教您是如何通过一个command token生成四个坐标呢？

**Comment by AlexDotHam** [comment]
四个坐标comand tokens concat在encoder的tokens上直出

**Comment by AlexDotHam** [comment]
用同一个command token或者用四个不同的command tokens没有本质区别，精度也没有什么区别

**Comment by self-memory** [comment]
非常感谢您的解答
