### ISSUE TITLE
Run pretrained model on a video

### ISSUE THREAD

**Issue by iMaTzzz** [MIV-XJTU/ARTrack#49]
First of all, thank you and congratulations for this amazing project !
Basically, I wanted to know if the code handles a video instead of datasets. Indeed, I'd like to try running the pretrained model on a 4K video to measure the inference time as well as the performance, to compare with other models. Thus, I wondered if this was possible and if so how ?

**Comment by AlexDotHam** [comment]
There is a solution in the previous issue [Issue](https://github.com/MIV-XJTU/ARTrack/issues/18).

I hope this is useful for u

**Comment by iMaTzzz** [comment]
Thank you ! I was also trying the pytracking framework so I'll definitely try yours as well ! I'll let you know if that works
