### ISSUE TITLE
pre_read_datasets.py的作用

### ISSUE THREAD

**Issue by llz-lian** [MIV-XJTU/ARTrack#52]
好像是跑一遍全部数据，预先读到cache里吗？

**Comment by AlexDotHam** [comment]
只针对COCO数据集做了Pre_read，因为数据集比较小，塞到cache里不复杂。整体来讲这个步骤的原因是，因为SOT的数据集比较大，过去需要放在固态里读取会比较快，所以都会做一些读取加速，现在固态很便宜，应该就没这个问题了。
