### ISSUE TITLE
关于SOT跟踪指标的小疑问

### ISSUE THREAD

**Issue by MrNeoBlue** [MIV-XJTU/ARTrack#55]
Hello，首先谢谢你们提供的算法，很棒的工作。我目前在研究算法的部署。
关于各个数据集上的指标，我有一个小问题：AUC和Norm Precision，哪一个更适合作为首要的评价指标。
我个人的理解是，Norm Precision应该更能表现跟踪的准确度，而AUC则更反应跟踪算法的鲁棒性？

**Comment by AlexDotHam** [comment]
看业务场景，如果你觉得目标大小在你的场景中非常多变，我认为NP更合适，如果你更注重能不能更稳定的保持目标在你的视野中，那我认为AUC更合适。
