### ISSUE TITLE
Conda dependencies in the yml file

### ISSUE THREAD

**Issue by Dualeco** [MIV-XJTU/ARTrack#58]
Is this the intended behavior that the conda environment yml file has various dependencies on conda and anaconda?

One of the side effects of this is that the created env refers to itself as "base"

**Comment by AlexDotHam** [comment]
Sorry for that, I am not familiar with the operation in conda or anaconda, I just use conda env export > xxx.yaml to export my environments, thus I am not sure about the question you mentioned whether regard to that.
