### ISSUE TITLE
BaselineQuesetion

### ISSUE THREAD

**Issue by Zsong1106** [MIV-XJTU/ARTrack#60]
When I am using the second stage of training to run the baseline model, when gradient backpropagation calculation loss occurs, it will prompt for an in place replacement error. I looked at the incorrect information and its dimension is [802768]. I first located the dimension in words'embeddings. I haven't made any changes either. Do you know where some specific details went wrong.
![1](https://github.com/MIV-XJTU/ARTrack/assets/37498830/24bf6c94-697c-4e13-b90a-fb452f8bca81)

**Comment by AlexDotHam** [comment]
I've found that bug before, but when I reproduced my code I didn't find that question. In my opinion, maybe you change the file in /lib/model/layers/head_seq.py 836 line,
 emb_weight = self.word_embeddings.weight.clone()
 There is a clone function to avoid that problem, you can try to use another clone operation.

**Comment by Zsong1106** [comment]
Thank you very much for your help. I found an environment issue in the code, which is a mismatch between the cuda version and yours. After switching to the cuda version, it can run smoothly
