### ISSUE TITLE
dependency conflicts

### ISSUE THREAD

**Issue by sunqimin** [MIV-XJTU/ARTrack#68]
When setting up the environment, executing the commands you provided results in many dependency conflicts among packages. How can this be resolved

**Comment by AlexDotHam** [comment]
I change a server and reproduced the enviroment, there maybe only numpy is conflicts with others, but not influence the execution of training and inference. Can you show me the detail of the problem you meet?

**Comment by sunqimin** [comment]
Sorry, I have turned  off , because there are conflicts between many dependencies. Parts of it like this：
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for argon2-cffi-bindings brotlipy cffi gevent _anaconda_depends anaconda pycparser cryptography: : 37Examining conflict for harfbuzz cairo: : 374it [7:43:59, 82.24s/it]                                                     Examining conflict for pytest spyder atomicwrites _anaconda_depends anaconda: : 382it [7:46:49, 50.48s/i
But it failed in the end. Now I am using pip to install packages one by one.

**Comment by AlexDotHam** [comment]
Sorry for that, i will retry and rebuild the environment in another server, and update the new environment support file.

**Comment by sunqimin** [comment]
I'm gonna bother you one more time，because I have a new problem like this：

$ sh tracking/run_video_demo.sh
test config:  {'MODEL': {'PRETRAIN_FILE': 'mae_pretrain_vit_base.pth', 'PRETRAIN
_PTH': 'D:\\SQM\\tracking\\ARTrack\\pretrained_models\\mae_pretrain_vit_base.pth
', 'PRENUM': 7, 'EXTRA_MERGER': False, 'RETURN_INTER': False, 'RETURN_STAGES': [
2, 5, 8, 11], 'BACKBONE': {'TYPE': 'vit_base_patch16_224', 'STRIDE': 16, 'MID_PE
': False, 'SEP_SEG': False, 'CAT_MODE': 'direct', 'MERGE_LAYER': 0, 'ADD_CLS_TOK
EN': False, 'CLS_TOKEN_USE_MODE': 'ignore', 'CE_LOC': [], 'CE_KEEP_RATIO': [], '
CE_TEMPLATE_RANGE': 'ALL'}, 'BINS': 400, 'RANGE': 2, 'ENCODER_LAYER': 3, 'NUM_HE
ADS': 12, 'MLP_RATIO': 4, 'QKV_BIAS': True, 'DROP_RATE': 0.1, 'ATTN_DROP': 0.0,
'DROP_PATH': 0.0, 'DECODER_LAYER': 6, 'HEAD': {'TYPE': 'PIX', 'NUM_CHANNELS': 76
8}}, 'TRAIN': {'LR': 4e-06, 'WEIGHT_DECAY': 0.05, 'EPOCH': 60, 'LR_DROP_EPOCH':
999, 'BATCH_SIZE': 8, 'NUM_WORKER': 4, 'OPTIMIZER': 'ADAMW', 'BACKBONE_MULTIPLIE
R': 0.1, 'GIOU_WEIGHT': 2.0, 'L1_WEIGHT': 0.0, 'FREEZE_LAYERS': [0], 'PRINT_INTE
RVAL': 1, 'VAL_EPOCH_INTERVAL': 10, 'GRAD_CLIP_NORM': 0.1, 'AMP': False, 'CE_STA
RT_EPOCH': 20, 'CE_WARM_EPOCH': 80, 'DROP_PATH_RATE': 0.1, 'SCHEDULER': {'TYPE':
 'step', 'DECAY_RATE': 0.1}}, 'DATA': {'SAMPLER_MODE': 'causal', 'MEAN': [0.485,
 0.456, 0.406], 'STD': [0.229, 0.224, 0.225], 'MAX_SAMPLE_INTERVAL': 200, 'MAX_G
AP': 300, 'MAX_INTERVAL': 5, 'INTERVAL_PROB': 0.0, 'TEMP': 2, 'TRAIN': {'DATASET
S_NAME': ['LASOT', 'GOT10K_vottrain', 'TRACKINGNET'], 'DATASETS_RATIO': [1, 1, 1
], 'SAMPLE_PER_EPOCH': 1000}, 'VAL': {'DATASETS_NAME': ['GOT10K_official_val'],
'DATASETS_RATIO': [1], 'SAMPLE_PER_EPOCH': 10000}, 'SEARCH': {'SIZE': 256, 'FACT
OR': 4.0, 'CENTER_JITTER': 3, 'SCALE_JITTER': 0.25, 'NUMBER': 36}, 'TEMPLATE': {
'NUMBER': 1, 'SIZE': 128, 'FACTOR': 2.0, 'CENTER_JITTER': 0, 'SCALE_JITTER': 0}}
, 'TEST': {'TEMPLATE_FACTOR': 2.0, 'TEMPLATE_SIZE': 128, 'SEARCH_FACTOR': 4.0, '
SEARCH_SIZE': 256, 'EPOCH': 60}}
4
4
4
Traceback (most recent call last):
  File "D:\SQM\tracking\ARTrack\tracking\video_demo.py", line 43, in <module>
    main()
  File "D:\SQM\tracking\ARTrack\tracking\video_demo.py", line 38, in main
    run_video(args.tracker_name, args.tracker_param, args.videofile, args.option
al_box, args.debug,
  File "D:\SQM\tracking\ARTrack\tracking\video_demo.py", line 21, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=
debug, save_results=save_results)
  File "D:\SQM\tracking\ARTrack\tracking\..\lib\test\evaluation\tracker.py", lin
e 174, in run_video
    tracker = self.create_tracker(params)
  File "D:\SQM\tracking\ARTrack\tracking\..\lib\test\evaluation\tracker.py", lin
e 63, in create_tracker
    tracker = self.tracker_class(params, self.dataset_name)
  File "D:\SQM\tracking\ARTrack\tracking\..\lib\test\tracker\artrack_seq.py", li
ne 22, in __init__
    network = build_artrack_seq(params.cfg, training=False)
  File "D:\SQM\tracking\ARTrack\tracking\..\lib\models\artrack_seq\artrack_seq.p
y", line 102, in build_artrack_seq
    missing_keys, unexpected_keys = model.load_state_dict(checkpoint["net"], str
ict=False)
KeyError: 'net'
What should i do？

**Comment by AlexDotHam** [comment]
The PRETRAIN_PTH in your file is wrong, it should be the Checkpoint we provide in https://drive.google.com/drive/folders/1KsH_MIZIdgjZpUZBmR4P88yeYDqM8yNW
but not the mae_pretrain you used.

**Comment by sunqimin** [comment]
May I ask what is the difference between artrack and artrack_seq？

**Comment by AlexDotHam** [comment]
In our paper, artrack represents the first-stage template matching training, this processing is for the quick converge of our sequential training, which is called artrack_seq, this training process is different from a conventional tracking pipeline, sampling time-continuous frames from a video, then conduct tracking frame-by-frame then training our artrack_seq.
