### ISSUE TITLE
about got10k

### ISSUE THREAD

**Issue by zxyyxzz** [MIV-XJTU/ARTrack#7]
请问一下为什么VIT-L在GOT10K上性能一下高出那么多呀？是因为自回归确实比较好吗？

另外请问一下，我可以私你邮箱拿到代码吗？

**Comment by AlexDotHam** [comment]
目前代码无法公布给您，我们希望给出一个完善的代码。
我们相信我们在论文中给出的逻辑判断已经能够说明我们的自回归框架具有先前工作不具备的优势，即基于显式轨迹的自回归框架尤其在Zero-shot tracking中具备强大的泛化能力，如您需要进一步的交流，可以直接发送信息至我的邮箱，我将竭尽所能回答您的任何疑问。

**Comment by zxyyxzz** [comment]
> 目前代码无法公布给您，我们希望给出一个完善的代码。 我们相信我们在论文中给出的逻辑判断已经能够说明我们的自回归框架具有先前工作不具备的优势，即基于显式轨迹的自回归框架尤其在Zero-shot tracking中具备强大的泛化能力，如您需要进一步的交流，可以直接发送信息至我的邮箱，我将竭尽所能回答您的任何疑问。

好的，感谢，那请问代码大概什么时候可以放出呢？
