### ISSUE TITLE
What happens if the target in the new training data set disappears midway?

### ISSUE THREAD

**Issue by jacky-rui** [MIV-XJTU/ARTrack#72]
We need to train and test the ARTrack on new dataset that object would be completely occluded. How do you handle this cases?

**Comment by AlexDotHam** [comment]
In fact, we don't do anything for that situation, but we find that, interestingly, if the target runs out of the view or is occlusion completely, the tracker tries to extend the search region (predict the target according to trajectory but with longer width and height). Thus even if we do nothing, when the target re-appears in the vision, we can re-track the target.
