### ISSUE TITLE
v2的seq

### ISSUE THREAD

**Issue by zhuhuzhenjing** [MIV-XJTU/ARTrack#75]
我想咨询一下v2的训练是抛弃掉随机采样训练，直接使用v1的序列及训练方法吗？仅仅是使用倒放的方式扩充了数据集？

**Comment by zhuhuzhenjing** [comment]
就还是两段式的训练，240个epoch非序列化训练+60个epoch序列化训练吗

**Comment by AlexDotHam** [comment]
是的，两段式训练
