### ISSUE TITLE
about attn_mask in artrackv2

### ISSUE THREAD

**Issue by ElliottZhen** [MIV-XJTU/ARTrack#76]
你好，请问ARTrackV2中的attn_mask,是类似于mixformer的那种在attention类中分开操作的，还是通过在注意力相似性矩阵上乘上mask，如果是后者，请问是在softmax之前乘吗？

**Comment by AlexDotHam** [comment]
是后者，并且是在softmax之前乘的

**Comment by AlexDotHam** [comment]
是的是的，我是直接用的torch的attn，所以那个mask我直接生成了一个下三角阵，然后批次的去改，比如把search每行都制为1，我是特意一个一个设计的。似乎torch是mask的就是-inf，剩下的用1还是0我记不太清了，你可以查一下torch的官方文档
