### ISSUE TITLE
Is the ARtrack code implemented in garbage?

### ISSUE THREAD

**Issue by LameYJ** [MIV-XJTU/ARTrack#77]
草泥马，

代码一堆bug，还要别人帮你debug，别人提问都要私聊，不敢正面回应。Artrack v2 在审稿时骗评审说会发布代码，结果被接收后就说有专利问题，现在还忽悠别人说Artrack v2代码会和v3一起在CVPR2025发布，
一下代码不见，一下给出和性能不一样的原始结果，说还在训练，一下再找工作，一下在实习，
一下还没毕业。
当人傻子啊。

The code is full of bugs, needing others to help debug. 
Private messages are insisted on when people ask questions, avoiding public responses. Artrack v2 lied about releasing the code during review, then blamed patents after acceptance. Now they claim the v2 code will be released with v3 at CVPR2025. 
Do they think we're fools?

**Comment by AlexDotHam** [comment]
谢谢您的提醒，我们会尽快公布代码

**Comment by AlexDotHam** [comment]
如果您还发现任何bug可以提醒我，我也并非没有正面回应，只是想邮件回复加个微信。
代码确实我无法公布，届时将在V3的论文中公布V2的训练和推理代码。
ARTrack一开始是两个代码分开运行的，合起来之后无法直接使用原先的checkpoint，我重新训练之后给出了对应的精度，您尽可以使用我给出的精度进行对比或者测试。
同时ARTrackB-256的精度并不比论文中的低，ARTrackL-384的精度其实只是在多个数据集间协调的区别，如果你训练过这个模型，你就会发现精度会在不同数据集间转换，重复出论文中的精度是一件困难对我来说也是无意义的事，同时不影响他的学术性。
对于您对我个人生平的有趣关注，您可以搜索我的脉脉或其他主页检索我阐述的是否真实。

**Comment by LameYJ** [comment]
> 如果您还发现任何bug可以提醒我，我也并非没有正面回应，只是想邮件回复加个微信。 代码确实我无法公布，届时将在V3的论文中公布V2的训练和推理代码。 ARTrack一开始是两个代码分开运行的，合起来之后无法直接使用原先的checkpoint，我重新训练之后给出了对应的精度，您尽可以使用我给出的精度进行对比或者测试。 同时ARTrackB-256的精度并不比论文中的低，ARTrackL-384的精度其实只是在多个数据集间协调的区别，如果你训练过这个模型，你就会发现精度会在不同数据集间转换，重复出论文中的精度是一件困难对我来说也是无意义的事，同时不影响他的学术性。 对于您对我个人生平的有趣关注，您可以搜索我的脉脉或其他主页检索我阐述的是否真实。

你拿一个性能差的模型ViT-B256来吹嘘可以训练出更好的效果，它的表现比你声称的SoTA L384还好？

复现论文中的精度对我来说既难又没意义，但这并不影响它的学术性。你的学术水平是靠吹的吗？

**Comment by AlexDotHam** [comment]
如果您需要的话，您大可以自己重新训练一个，我相信不会比我的精度差多少，我也确实没那么多时间一直训这个模型，只是把模型最后一个epoch的精度测出来直接发了过来，我训练一次需要一周的时间，如果您有多余的机器，您自然可以训练，我没有必要在这种精度上作假，我把我大的模型精度写高，把小的模型精度写低，这件事情有什么意义呢？在当时我的base-256已经是SOTA了，我多此一举的目的是什么呢？况且GOT-10k与TrackingNet的精度都是在评测网站上得到的，您也可以查看对应的评测网站，我只是没有那么多时间重复在一个工作上，如果您需要同时实习、做研究、找工作的话，您又是否能和我一样抽出时间回复Github呢？

**Comment by LameYJ** [comment]
> 如果您需要的话，您大可以自己重新训练一个，我相信不会比我的精度差多少，我也确实没那么多时间一直训这个模型，只是把模型最后一个epoch的精度测出来直接发了过来，我训练一次需要一周的时间，如果您有多余的机器，您自然可以训练，我没有必要在这种精度上作假，我把我大的模型精度写高，把小的模型精度写低，这件事情有什么意义呢？在当时我的base-256已经是SOTA了，我多此一举的目的是什么呢？况且GOT-10k与TrackingNet的精度都是在评测网站上得到的，您也可以查看对应的评测网站，我只是没有那么多时间重复在一个工作上，如果您需要同时实习、做研究、找工作的话，您又是否能和我一样抽出时间回复Github呢？

学习了，大家以后被质疑实作和真实性时，就回复一句“很忙，没空，明年CVPR会release”就行。
既然你这么多事要忙还不能满足学术要求，要不考虑离开吧。

**Comment by AlexDotHam** [comment]
由于您的逻辑已经自洽，我相信没有什么可以说服您了，除非我能拿出能推理出一模一样精度的checkpoint，但是由于您并不关注Large-384上在Lasot和GOT上的精度提升，也不在意我给出的理由（这个理由也许您觉并不合理）。同时您不认为V2会开源，也许是基于过去您对V1模型的认识，也许是基于您无法复现V2导致的焦躁，我认为您都可以通过使用其他baseline的方式来创造新的学术方向，或者您可以写一篇技术报告来抨击我们的方案，这都是现实的解决方案。如果您也同样面对我所需要完成的事情，我相信您一定不会说出今天这样的话，我相信对于很多论文作者来说开源都是一件很麻烦的事情，因为不仅需要回复大家的问题，还需要对自己的言行负责，同时这件事情相对我一个研究生来说也是吃力不讨好的，对我的收益非常的低，但我选择做了这件事情，我希望您能理解并对我多一些宽容。同时我不会删除您的issue，直到我开源我的V2代码，您都可以随时来向我发出质疑，您的出现也是对我的一种鞭策。

**Comment by LameYJ** [comment]
> 由于您的逻辑已经自洽，我相信没有什么可以说服您了，除非我能拿出能推理出一模一样精度的checkpoint，但是由于您并不关注Large-384上在Lasot和GOT上的精度提升，也不在意我给出的理由（这个理由也许您觉并不合理）。同时您不认为V2会开源，也许是基于过去您对V1模型的认识，也许是基于您无法复现V2导致的焦躁，我认为您都可以通过使用其他baseline的方式来创造新的学术方向，或者您可以写一篇技术报告来抨击我们的方案，这都是现实的解决方案。如果您也同样面对我所需要完成的事情，我相信您一定不会说出今天这样的话，我相信对于很多论文作者来说开源都是一件很麻烦的事情，因为不仅需要回复大家的问题，还需要对自己的言行负责，同时这件事情相对我一个研究生来说也是吃力不讨好的，对我的收益非常的低，但我选择做了这件事情，我希望您能理解并对我多一些宽容。同时我不会删除您的issue，直到我开源我的V2代码，您都可以随时来向我发出质疑，您的出现也是对我的一种鞭策。

作者表示：
「我相信对很多论文作者来说，开源都是件麻烦事，因为不仅要回复大家的问题，还得对自己的言行负责。」
还第一次听到，见识了。

还有别再造谣了，哪句说不在意LaSOT和GOT提升？我有问你会不会release v2吗？要release怎么不现在release，一年后才implement出来啊？你的patent一年就过期了可以release了？你明年买通评审了啊，还跟别人说CVPR2025会看到v3喔。

**Comment by AlexDotHam** [comment]
其实您的逻辑非常混乱，您一开始说我忽悠别人代码会发布，我如今告诉您我会发布，您又说您并没有提问，也许对您来说只有问句才是质疑的一种。您说我不敢正面回答别人的问题，可是您开了一个刚注册的匿名账号来在仓库下提问。我回复了您所有的问题，您依然完全没有完整的表达您的逻辑链条是什么。您说一年后这个pattern就过期了，如果我的开源只是为了方便您的利益，那您为什么来攻击我呢？是因为我妨碍了您获得什么吗？那么您为什么要执迷于从我身上得到答案，而不是自己去探索呢？或者说您为什么不直接去复现我的代码呢？我相信您一定怀疑代码的真实性，我告知您代码会开源，是为了让您理解这份代码是真实存在的，您似乎没有完全理解我的含义。即使CVPR2025并不中稿，也不会影响我开源，我会在CVPR截稿后开放代码和V3的论文。跟您说了这么多，我也理解您现在的心情，请您先放下您的情绪，理性的思考然后作出您自己的判断。我不现在放出代码，当然有我的原因，我没有必要告知你，如果全世界是围着您转的，那么自然您一定全知全能，能猜测得到我不开的理由。如果不是围着您转的，您至少应该给出您的逻辑和理由，这样别人才能有效的和您沟通。

**Comment by LameYJ** [comment]
> 其实您的逻辑非常混乱，您一开始说我忽悠别人代码会发布，我如今告诉您我会发布，您又说您并没有提问，也许对您来说只有问句才是质疑的一种。您说我不敢正面回答别人的问题，可是您开了一个刚注册的匿名账号来在仓库下提问。我回复了您所有的问题，您依然完全没有完整的表达您的逻辑链条是什么。您说一年后这个patent就过期了，我只是在陈述，可以通过V3的代码来绕过这个问题，我希望您可以理解这里面的逻辑关系。您为什么要执迷于从我身上得到答案，而不是自己去探索呢？或者说您为什么不直接去复现我的代码呢？我相信您一定怀疑代码的真实性，我告知您代码会开源，是为了让您理解这份代码是真实存在的，您似乎没有完全理解我的含义。即使CVPR2025并不中稿，也不会影响我开源，我会在CVPR截稿后开放代码和V3的论文。跟您说了这么多，我也理解您现在的心情，请您先放下您的情绪，理性的思考然后作出您自己的判断。我不现在放出代码，当然有我的原因，我没有必要告知你，如果全世界是围着您转的，那么自然您一定全知全能，能猜测得到我不开的理由。如果不是围着您转的，您至少应该给出您的逻辑和理由，这样别人才能有效的和您沟通。

急了啊?
不是开始说CVPR25会看到，现在改口说25没中也可以release喔。
是别人要求你release code和pretrain weight，你还造谣成是我要求的。
别人问艰深问题你回答不出来就让别人私信啊？
还勒索别人要按星啊？
搞笑了，你自己在论文里声称你的东西能work，现在要别人自己去探索。

**Comment by LameYJ** [comment]
> 其实您的逻辑非常混乱，您一开始说我忽悠别人代码会发布，我如今告诉您我会发布，您又说您并没有提问，也许对您来说只有问句才是质疑的一种。您说我不敢正面回答别人的问题，可是您开了一个刚注册的匿名账号来在仓库下提问。我回复了您所有的问题，您依然完全没有完整的表达您的逻辑链条是什么。您说一年后这个patent就过期了，我只是在陈述，可以通过V3的代码来绕过这个问题，我希望您可以理解这里面的逻辑关系。您为什么要执迷于从我身上得到答案，而不是自己去探索呢？或者说您为什么不直接去复现我的代码呢？我相信您一定怀疑代码的真实性，我告知您代码会开源，是为了让您理解这份代码是真实存在的，您似乎没有完全理解我的含义。即使CVPR2025并不中稿，也不会影响我开源，我会在CVPR截稿后开放代码和V3的论文。跟您说了这么多，我也理解您现在的心情，请您先放下您的情绪，理性的思考然后作出您自己的判断。我不现在放出代码，当然有我的原因，我没有必要告知你，如果全世界是围着您转的，那么自然您一定全知全能，能猜测得到我不开的理由。如果不是围着您转的，您至少应该给出您的逻辑和理由，这样别人才能有效的和您沟通。

还有，你欺骗reviewers说要release code，现在说专利问题不开源了，要不要自己申请撤稿啊？

**Comment by AlexDotHam** [comment]
您说的问题我已经回复过您很多遍了，我会开源这份代码。一篇学术论文不会因为是否开源就被拒绝，如果审稿人根据这一点来评价一篇论文所具备的价值是非常不专业的，这并不涉及任何学术不端行为，我为什么需要申请撤稿呢？
我更改留言中是因为我对您上一个回答中的问题出现了错误的理解，我很快的修正了回答，并不影响我整个回答的逻辑。
不知道您是否还有其他问题？以及您的诉求到底是什么？

**Comment by LameYJ** [comment]
> 您说的问题我已经回复过您很多遍了，我会开源这份代码。一篇学术论文不会因为是否开源就被拒绝，如果审稿人根据这一点来评价一篇论文所具备的价值是非常不专业的，这并不涉及任何学术不端行为，我为什么需要申请撤稿呢？ 我更改留言中是因为我对您上一个回答中的问题出现了错误的理解，我很快的修正了回答，并不影响我整个回答的逻辑。 不知道您是否还有其他问题？以及您的诉求到底是什么？

一篇学术论文不会因为是否开源就被拒绝，但现在是你先欺骗审稿人说你要公布代码，他们接受之后你才反悔。是你逻辑有问题。你说可以release，还扯上专利干嘛？你那是一年过期的专利啊？

如果审稿人根据这一点来评价一篇论文的价值是非常不专业的，你这才是欺骗，比较没品吧。别跟我说审稿标准里没有reproducibility这一项。

**Comment by AlexDotHam** [comment]
我已经说过很多次了，我会开源代码，我难以理解您为什么不断的重复这句话，我已经告知您了，我会开源代码。
我刚才已经告诉过您了，我们可以通过开源V3的代码跳过这部分问题。您为什么不能理解呢？
我提出了我设想的解决方案，您如果不接受，那不接受的原因是什么呢？
除此之外您还有其他问题吗？

**Comment by LameYJ** [comment]
> 我已经说过很多次了，我会开源代码，我难以理解您为什么不断的重复这句话，我已经告知您了，我会开源代码。 我刚才已经告诉过您了，我们可以通过开源V3的代码跳过这部分问题。您为什么不能理解呢？ 我提出了我设想的解决方案，您如果不接受，那不接受的原因是什么呢？ 除此之外您还有其他问题吗？

可以通过v3来规避你欺骗审稿人这个问题吗？
这么厉害。
啊，明年不就是通过v4来规避v3的问题了吗？
还是你又要忙代码又要消失了？

**Comment by AlexDotHam** [comment]
您的逻辑又绕回来了，如果您不相信我会开源代码，我们的讨论没有任何必要，因为您已经假定了这个结果，我没法给您任何解决方案，所以这才涉及到欺骗审稿人以及v3、v4的问题，既然您已经不相信了，无论我怎么向您陈述或保证，您都不接受，那您显然不是来进行提问。如果您相信我会开源，那就不存在您阐述的这个逻辑，我能理解您的心情，请您自行判断。请问您还有其他问题吗？

**Comment by LameYJ** [comment]
> 您的逻辑又绕回来了，如果您不相信我会开源代码，我们的讨论没有任何必要，因为您已经假定了这个结果，我没法给您任何解决方案，所以这才涉及到欺骗审稿人以及v3、v4的问题，既然您已经不相信了，无论我怎么向您陈述或保证，您都不接受，那您显然不是来进行提问。如果您相信我会开源，那就不存在您阐述的这个逻辑，我能理解您的心情，请您自行判断。请问您还有其他问题吗？

你在别人回复中说v2不会开源，v3也不会像v2一样，因为有专利问题。那为什么现在又能开源了，还提到CVPR 25，我问你哪来的CVPR 25的v3，你才解释说即使不中也会开源。但你说v2不可能开源啊，还是说专利一年就过期了？你用专利因此无法开源，不就代表v2是垃圾吗？因为使用v2的研究者也因此设计了专利不能开源。一个不可能开源的项目你让别人相信你？还是你的专利申请是假的？不要再骗人了，好吗？

你欺骗reviewer和社群，问你为什么不诚实，谁在乎你有没有开源，你又在狡辩，还问别人有没有问题。

**Comment by dqs932** [comment]
没搞懂啊，觉得人家这代码写的不好或者有bug，最积极的做法应当是提出疑问，或提出建设性意见，也可以不复现，不关注，不理睬，还可以去研究其他项目，或者自己写个更好的代码贡献出来，而不是拉东扯西，胡言乱语，无端指责与谩骂。

人家作者已经贡献了宝贵的代码资源，还附上了详尽的说明文档，面对疑问，更是以极大的耐心和礼貌一一解答，可以说仁至义尽，真心诚意，这份努力与诚意，理应得到应有的尊重与感激。

恰恰是没做什么实质性贡献的人，却动辄对他人成果指手画脚、恶语相向、连喷带骂，丢人现眼。不仅是对他人劳动成果的轻视，更是对自身素养与风度的极大贬低，实属令人不齿，自取其辱。

**Comment by LameYJ** [comment]
> 没搞懂啊，觉得人家这代码写的不好或者有bug，最积极的做法应当是提出疑问，或提出建设性意见，也可以不复现，不关注，不理睬，还可以去研究其他项目，或者自己写个更好的代码贡献出来，而不是拉东扯西，胡言乱语，无端指责与谩骂。
> 
> 人家作者已经贡献了宝贵的代码资源，还附上了详尽的说明文档，面对疑问，更是以极大的耐心和礼貌一一解答，可以说仁至义尽，真心诚意，这份努力与诚意，理应得到应有的尊重与感激。
> 
> 恰恰是没做什么实质性贡献的人，却动辄对他人成果指手画脚、恶语相向、连喷带骂，丢人现眼。不仅是对他人劳动成果的轻视，更是对自身素养与风度的极大贬低，实属令人不齿，自取其辱。

你跟他一夥詐騙的嗎？

「人家作者已經貢獻了寶貴的代碼資源？」
v2代碼和權重在哪裡？有沒有詐騙reviewer說要開源，結果被接受後才在這裡說專利問題不開源了？還說會在CVPR2025開源v3，那v2呢？不是不敢講，逃避我問的問題嗎？

你先跟我說v2在哪。

你們是一夥詐騙的吧。

**Comment by LameYJ** [comment]
> > 没搞懂啊，觉得人家这代码写的不好或者有bug，最积极的做法应当是提出疑问，或提出建设性意见，也可以不复现，不关注，不理睬，还可以去研究其他项目，或者自己写个更好的代码贡献出来，而不是拉东扯西，胡言乱语，无端指责与谩骂。
> > 人家作者已经贡献了宝贵的代码资源，还附上了详尽的说明文档，面对疑问，更是以极大的耐心和礼貌一一解答，可以说仁至义尽，真心诚意，这份努力与诚意，理应得到应有的尊重与感激。
> > 恰恰是没做什么实质性贡献的人，却动辄对他人成果指手画脚、恶语相向、连喷带骂，丢人现眼。不仅是对他人劳动成果的轻视，更是对自身素养与风度的极大贬低，实属令人不齿，自取其辱。
> 
> 你跟他一夥詐騙的嗎？
> 
> 「人家作者已經貢獻了寶貴的代碼資源？」 v2代碼和權重在哪裡？有沒有詐騙reviewer說要開源，結果被接受後才在這裡說專利問題不開源了？還說會在CVPR2025開源v3，那v2呢？不是不敢講，逃避我問的問題嗎？
> 
> 你先跟我說v2在哪。
> 
> 你們是一夥詐騙的吧。

你们有没有听过一本正经讲干话这句话？
你们现在就是，
一个我问v2在哪，为什么骗reviewer，他回答v3会开源，但又在别处说v3跟v2不一样；
一个看同伙被喷，还瞎掰说v2有开源，然后一样逃避同伙诈骗社群和reviewer的问题。
不是讲得一本正经就能掩盖你们内容不实的信息啊。

**Comment by AlexDotHam** [comment]
您的幻觉还是有些严重，您完全可以不去理会我，因为我已经告诉您了我所有的逻辑，您在其中摘选出了您想看到的知识，然后舍弃了您不想看到的内容，您可以再找任何一个人来评论这件事情，包括您的朋友，但我猜想您通过匿名的方式来回复，一定是不想让人知道您做了这件事，当然也可能您害怕我会报复您，因为我必然有非常强大的能量，才能让您在学术界无法存在。您可以自行判断这件事情，您不需要无端抨击一个路人。说起来我很难理解您为什么选择匿名，我相信如果您认为您所说的事情是正义的是合理的，同时您是一个认为别人需要呼吁同伴来声援自己的人，不然您也不会认为这位女生是我的“同伙”，那么您匿名的意义在哪里呢？因为要么您认为您的逻辑是错误的，因此您不想让您的同伴知道您的存在，要么您的逻辑是正确的，但是您认为别人一定是找了同伴声援自己，而不是有人看不惯您的言论对您进行了指责，那么您自身为什么不找您的同伴声援您自己呢？您不能同时让两个逻辑都成立，这让人难以理解。或者说如果您对我的评价指标和对您的指标并不一致，我认为这我们就没有什么再讨论的必要了。您的言行不一我从头到尾已经表达过非常多次了，您的所有问题我都给出了答案，我希望您能理性一点，做一个能让他人理解的人。

**Comment by dqs932** [comment]
> > 没搞懂啊，觉得人家这代码写的不好或者有bug，最积极的做法应当是提出疑问，或提出建设性意见，也可以不复现，不关注，不理睬，还可以去研究其他项目，或者自己写个更好的代码贡献出来，而不是拉东扯西，胡言乱语，无端指责与谩骂。
> > 人家作者已经贡献了宝贵的代码资源，还附上了详尽的说明文档，面对疑问，更是以极大的耐心和礼貌一一解答，可以说仁至义尽，真心诚意，这份努力与诚意，理应得到应有的尊重与感激。
> > 恰恰是没做什么实质性贡献的人，却动辄对他人成果指手画脚、恶语相向、连喷带骂，丢人现眼。不仅是对他人劳动成果的轻视，更是对自身素养与风度的极大贬低，实属令人不齿，自取其辱。
> 
> 你跟他一伙诈骗的吧？ “人家作者已经贡献了宝贵的代码资源？”
> 
> v2代码和权重在哪里？ 有没有诈骗reviewer说要开源， 结果被接受后才说因为专利问题不再开源了？ 还说会在CVPR2025开源v3，那v2 呢？ 是不是不敢讲，逃避我问的问题吗？
> 
> 妳先告诉我v2在哪里。
> 
> 你们是一伙诈骗的吧。
> 
> 诈骗集团同伙不回答为什么骗人， 还要平民有实质贡献， 才想回答为什么施行诈骗啊？


你咋总张口闭口诈骗的😂😂😂，首先声明，我跟作者不认识，我只是看到评论感到很可气，你一个大男人，心胸如此狭隘，不知道你从哪得到的结论说我跟他一伙诈骗，我又诈骗了你什么？我怎么就诈骗了？是不是你对所有反对你的人都说他们是一伙？他们都是诈骗？你要不报警把我抓起来？？？？

只是看不惯你在评论区骂人才评论的。真是无语了......又是说诈骗又是说买通评审，这种话怎么说出口的，人家论文以后录用了就是买通评审？你怎么不买通评审？说话都这么不负责任？诽谤就治不了你？现在都什么年代了，还有你这种小人，打横炮使邪力，你天天酸溜溜，又为科研作了什么贡献？既然没贡献，逼逼赖赖什么？显得你长的有嘴？有力气没地方使，不如去包点地种。

再说，代码公开不公开是作者权利，人家的劳动成果，凭什么给你，你瞎激动什么，cvpr不公开的多了去了，你一个一个都去喷人家诈骗？真是头脑简单。。。

**Comment by dqs932** [comment]
> > > > 没搞懂啊，觉得人家这代码写的不好或者有bug，最积极的做法应当是提出疑问，或提出建设性意见，也可以不复现，不关注，不理睬，还可以去研究其他项目，或者自己写个更好的代码贡献出来，而不是拉东扯西，胡言乱语，无端指责与谩骂。
> > > > 人家作者已经贡献了宝贵的代码资源，还附上了详尽的说明文档，面对疑问，更是以极大的耐心和礼貌一一解答，可以说仁至义尽，真心诚意，这份努力与诚意，理应得到应有的尊重与感激。
> > > > 恰恰是没做什么实质性贡献的人，却动辄对他人成果指手画脚、恶语相向、连喷带骂，丢人现眼。不仅是对他人劳动成果的轻视，更是对自身素养与风度的极大贬低，实属令人不齿，自取其辱。
> > > 
> > > 
> > > 你跟他一伙诈骗的吧？ “人家作者已经贡献了宝贵的代码资源？”
> > > v2代码和权重在哪里？ 有没有诈骗reviewer说要开源， 结果被接受后才说因为专利问题不再开源了？ 还说会在CVPR2025开源v3，那v2 呢？ 是不是不敢讲，逃避我问的问题吗？
> > > 妳先告诉我v2在哪里。
> > > 你们是一伙诈骗的吧。
> > > 诈骗集团同伙不回答为什么骗人， 还要平民有实质贡献， 才想回答为什么施行诈骗啊？
> > 
> > 
> > 你咋总张口闭口诈骗的😂😂😂，首先声明，我跟作者不认识，我只是看到评论感到很可气，你一个大男人，心胸如此狭隘，不知道你从哪得到的结论说我跟他一伙诈骗，我又诈骗了你什么？我怎么就诈骗了？是不是你对所有反对你的人都说他们是一伙？他们都是诈骗？你要不报警把我抓起来？？？？
> > 只是看不惯你在评论区骂人才评论的。真是无语了......又是说诈骗又是说买通评审，这种话怎么说出口的，人家论文以后录用了就是买通评审？你怎么不买通评审？说话都这么不负责任？诽谤就治不了你？现在都什么年代了，还有你这种小人，打横炮使邪力，你天天酸溜溜，又为科研作了什么贡献？既然没贡献，逼逼赖赖什么？显得你长的有嘴？有力气没地方使，不如去包点地种。
> > 再说，代码公开不公开是作者权利，人家的劳动成果，凭什么给你，你瞎激动什么，cvpr不公开的多了去了，你一个一个都去喷人家诈骗？真是头脑简单。。。
> 
> 你不要搞不清楚状况好吧，是他先说要公开代码的，也没跟审稿人说有专利不能公开代码。一开始不答应公开不就没事了吗？让审稿人觉得可以复现，结果被接受了才说有专利问题不能公开？
> 
> 还有，你们这种不公开源代码的习惯，难怪把这个社区搞得一团糟。
> 
> 你是路人，有看过他之前在其他地方回复的所有评论吗？没有啊，路人怎么能这么快就帮他辩护呢？帮凶不是犯罪那是什么？
> 
> 对了，你刚刚不是说他有公开？怎么现在说不公开也可以了？

所以你骂人社区就不一团糟？好家伙，我又成帮凶犯罪了。。。。。。

**Comment by iMaTzzz** [comment]
I don't speak Chinese but from what I can translate, this is ridiculous. I highly appreciate your work you made on ARTrack and even though ARTrackv2 is still unavailable, I'm still thankful for your kind answers.

Please ignore this guy, he isn't worth anyone's time. He is probably a troll that needs your work for his own benefit.

**Comment by iMaTzzz** [comment]
>I asked why he didn't inform the reviewers that the ARTrackv2 code would not be released due to a patent.

That I understand but he doesn't owe us anything, he can do whatever he wants and you should be thankful that he released the code of ARTrackv1 as well as the checkpoints.

>You said u highly appreciate ARTrackv1???

Indeed, I do, it works really well!

>I asked why he committed fraud.
When people asked about the ARTrackv2 code,
he responded that the ARTrackv3 code would be available at CVPR 2025.

I don't see why it's fraud, is there a law I'm unaware of which stipulates that he has to publish the code ?

> You said I probably a troll that needs this garbage for myown benefit???

Well if you didn't need ARTrackv2, you wouldn't cry like this. Grow up

> Can you also explain why you are only following this guy??

Because that's the only open source object tracking model that I could use so I'm following him to have any updates on ARTrackv2

> A TikTok person cannot speak Chinese???

That's not me... I don't work at Tik Tok nor I speak Chinese. I just don't understand why you need to insult someone this bad for something it doesn't have to do.

> Ahhh???

Taiwan number 1 !!!
