### ISSUE TITLE
二阶段测试的时候PRETRAIN_PTH

### ISSUE THREAD

**Issue by zhuhuzhenjing** [MIV-XJTU/ARTrack#78]
我想咨询一下二阶段测试的时候，PRETRAIN_PTH是一阶段240epoch的结果模型，还是二阶段60epoch的结果模型，非常感谢

**Comment by AlexDotHam** [comment]
这个应该不影响推理的性能，因为二阶段推理时真正加载的pth应该是二阶段60epoch的结果模型，并且是在tracker中进行的加载而不是在模型创建时，理论上这里不加载任何模型也是可以的，但是我的代码可能没有考虑这种情况。因此结论是随便加载一个即可，都不会影响最终的性能。

**Comment by zhuhuzhenjing** [comment]
好的，谢谢

**Comment by zhuhuzhenjing** [comment]
您好，请问您在文章附录中生成的热力图可视化是通过什么工具制作的




cozen0
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MIV-XJTU/ARTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 中午12:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MIV-XJTU/ARTrack] 二阶段测试的时候PRETRAIN_PTH (Issue #78)





 
Closed #78 as completed.
