### ISSUE TITLE
一个关于GOT10k的基础问题

### ISSUE THREAD

**Issue by yuyangpoi** [MIV-XJTU/ARTrack#81]
你好，很棒的工作！
我有一个关于GOT10k的基础问题，我在检查该数据集的时候，发现存在一些序列（如GOT-10k_Train_008630及其相邻的一些序列）的前几帧或十几帧是相同的，并且标注框无法和目标对应。

请问这是数据的问题吗？或者也许是我的读取有问题？期待你的回复，谢谢。

![image](https://github.com/user-attachments/assets/652e76f3-9d28-4dba-8b90-11a8cfb33d5d) 
![image](https://github.com/user-attachments/assets/e16a089a-f4c3-45ab-94c1-35edae078721)

**Comment by AlexDotHam** [comment]
我在其他跟GOT10k相关的问题中看到过类似的问题，我在做试验的时候其实没有逐个视频去检查，因此可能这个问题是真实存在的，我认为最好的解决方法，是把这些视频删掉。
