### ISSUE TITLE
关于ARTrackV3

### ISSUE THREAD

**Issue by Jacky-F** [MIV-XJTU/ARTrack#83]
你好，请问您的v3工作预计什么时候发布呢？感谢您的回答！

**Comment by AlexDotHam** [comment]
V3大概会投今年ICLR或者CVPR，看能不能赶上了。
最近应该会先放V2的推理代码，但是为Mindspore版本，这个是根据我们的基金要求的（Mindspore OpenFunding）。如果您有需要可以联系我的邮件或微信。

**Comment by Jacky-F** [comment]
好的，感谢！其次还想询问一些v2工作的细节，v2工作中将轨迹信息和command的信息一并输入encoder后仅输出了command的结果，请问轨迹信息加入运算后的输出结果直接丢弃嘛？还是说轨迹信息和command的信息是结合输入的？感谢您的解答！

**Comment by AlexDotHam** [comment]
轨迹信息和command在concat后输入到encdoer中，随后丢弃掉轨迹信息的output，仅关注command的四个tokens的输出。
