### ISSUE TITLE
How to set the tgt mask in the decoder of ARTRackv2?

### ISSUE THREAD

**Issue by yuyangpoi** [MIV-XJTU/ARTrack#84]
How to set the tgt mask in the decoder of ARTrackv2 after removing intra-frame autoregression?

**Comment by AlexDotHam** [comment]
We have open the inference code of ARTrackV2, you can see that in the README, a Temporal Code is released. Then the mask of ARTrackV2 is in lib/base_backbone.py, the whole pipeline is in that py file.
