### ISSUE TITLE
Inference slow

### ISSUE THREAD

**Issue by Ocean23333** [MIV-XJTU/ARTrack#85]
Hello, i followed the Readme.md and only made a slight modification(pycocotools==2.0.8 ). 
When i ran the test.py on 4090 gpus with the script：
python test.py artrack_seq artrack_seq_256_full --dataset lasot --threads 0 --num_gpus 1
or
python test.py artrack_seq artrack_seq_256_full --dataset lasot --threads 8 --num_gpus 2
i got about 14 fps。
I dont know where‘s problem up.
I hope you can provide some suggestions, thank you in advance!

**Comment by AlexDotHam** [comment]
The question about the inference speed may come from the CPU, i use the official code in 3090 server, i get about 18 FPS, when use the inference test code (like in OSTrack), i get the FPS about 26.

**Comment by AlexDotHam** [comment]
By the way, the inference speed of ARTrack is really slow, it comes from the inter-frame autoregressive, in other words you need to decode the trajectory sequence from x_min, to y_max. The four time decode make the speed unacceptable.

**Comment by Ocean23333** [comment]
Thank you for your rapid reply, i am trying to run the inference in the V2 version(temporal code).
Looking forward to the release of your V3 paper and code.Great work!
