### ISSUE TITLE
Raw Results of ARTrack_large_384_full or ARTrackv2

### ISSUE THREAD

**Issue by yangchris11** [MIV-XJTU/ARTrack#87]
Thank you for your work!

I wonder if you can also provide the raw trakcing results of ARTrack_large_384_ful or ARTrackv2 l?

**Comment by AlexDotHam** [comment]
For ARTrack_large_384_full, sorry for that we only provide the checkpoint. In future we will provide raw results, however recently I don't have enough compute resource for that (CVPR 2025 is coming), after that I will provide the raw result. For ARTrackV2, I will provide the raw_result before tomorrow, but we do not plan to provide the ARTrackV2-L's checkpoint and raw_result before the ARTrackV3 is published.

**Comment by AlexDotHam** [comment]
Sorry for lately update for the raw_result, i have released the raw_result of ARTrackV2.
