### ISSUE TITLE
二阶段的测试结果没有一阶段的测试结果好

### ISSUE THREAD

**Issue by Feng0o7** [MIV-XJTU/ARTrack#94]
ARTrack V2:
![image](https://github.com/user-attachments/assets/81426a7d-b22e-4206-99eb-64a3a56f265f)
你们有出现这样的问题吗？
还有就是两个阶段的模型是不一样的吗？

**Comment by AlexDotHam** [comment]
二阶段的训练是加载了一阶段的训练模型后再训练的结果，所以应该效果不会差很多，我自己训练的过程中没有出现过精度下降的情况，您一阶段的精度也基本是正常的。
两个阶段的模型略有不同，区别在于二阶段额外增加了一个Decoder去重建外观特征，其他部分是一致的。

**Comment by Feng0o7** [comment]
> 二阶段的训练是加载了一阶段的训练模型后再训练的结果，所以应该效果不会差很多，我自己训练的过程中没有出现过精度下降的情况，您一阶段的精度也基本是正常的。 两个阶段的模型略有不同，区别在于二阶段额外增加了一个Decoder去重建外观特征，其他部分是一致的。 通常来说在GOT-10k上，二阶段训练会有3.5%左右的AO提升。
> 
> 我猜测您可能是二阶段训练后，使用了一阶段的推理框架进行了推理，而没有使用二阶段的config，不知道是否是这样？
这个是artrackv2_seq_256-got的配置文件内容
![image](https://github.com/user-attachments/assets/8e0f9601-f505-4784-a206-92aafb041cce)
这个是训练时输入的命令
![image](https://github.com/user-attachments/assets/aeb544a9-38ce-4261-a03c-84d0030bdb96)
我也是搞不清楚了，为啥精度能下降。
对了 还有一个问题就是ARTrack-main/lib/train/actors/artrackv2_seq.py中 if len(outputs['pre_seq']) != 8:的8是不是就是self.batch_size呀，我batch改小后就有问题，不能运行了。
![image](https://github.com/user-attachments/assets/7ebd7421-4a7e-481c-bd41-36c4ab57093e)

**Comment by AlexDotHam** [comment]
1、 您训练时使用的是单卡吗？由于序列训练实际上反传时一个视频具有相似的梯度，因此如果不使用多卡的话，仅增加bs，会使得多帧的loss趋于相似，这可能会导致训练崩溃，我将尝试一下如果仅使用单卡是否会存在精度下降的情况，可能需要您等待一定时间。
2、这个bs如果您更该数字后，将判断中的8改成对应数字即可。

**Comment by Feng0o7** [comment]
> 1、 您训练时使用的是单卡吗？由于序列训练实际上反传时一个视频具有相似的梯度，因此如果不使用多卡的话，仅增加bs，会使得多帧的loss趋于相似，这可能会导致训练崩溃，我将尝试一下如果仅使用单卡是否会存在精度下降的情况，可能需要您等待一定时间。如果您关注到trainer中的loss反传，它实际上是逐个加入了每一段视频的loss，这就使得梯度崩溃。我举得简单的例子，假如您使用了batchnorm（我们使用的是layernorm，仅作为一个例子），由于您梯度反传时是一个视频过一次batchnorm，那么就会导致batch上的均值和方差出现偏移（由于一个视频的特征相似），这会使得下一次训练时梯度和方差无法和上一个视频对齐，进而使得模型去拟合复杂的均值和方差变换，而忽视了学习tracking本身。您可以尝试将逐个加入的梯度换成N个视频一加入反传的梯度中，这样会增加显存占用，但可以极大的增加loss的多样性，希望会有效果。 具体来说，您可以修改\lib\train\trained\ltr_seq_trainer_v2.py 中120行的bs_backward，修改为您需要的数字，1仅是为了方便降低显存提高单个视频的帧数，这可能是一个trade off
> 
> 2、这个bs如果您更该数字后，将判断中的8改成对应数字即可。

是的，我使用的是一张A100（40G显存）的GPU，那真是麻烦您了！

**Comment by AlexDotHam** [comment]
![image](https://github.com/user-attachments/assets/940faacb-e2b3-45ea-ad8d-0456475b9040)
很奇怪，我训练了5个epoch用单卡，似乎也是长点的。。

**Comment by Feng0o7** [comment]
> ![image](https://private-user-images.githubusercontent.com/106003828/392837117-940faacb-e2b3-45ea-ad8d-0456475b9040.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Nzg2MjUsIm5iZiI6MTczMzQ3ODMyNSwicGF0aCI6Ii8xMDYwMDM4MjgvMzkyODM3MTE3LTk0MGZhYWNiLWUyYjMtNDVlYS1hZDhkLTA0NTY0NzViOTA0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTQ1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWZjMTg1YzI2ZjM5N2IyZTc5NDRmZmUyOTJhN2U2MTNmNTlmMWJjMDcwNDhmY2RlMTAzM2E4YjAzMTNjYzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LVz0wK2VoORlqq4n2j97fRCA_gR725mwK_j2Av6WzW4) 很奇怪，我训练了5个epoch用单卡，似乎也是长点的。。

那就是我本地的问题了，我再尝试下。非常感谢回答，麻烦您了！

**Comment by AlexDotHam** [comment]
我把二阶段单卡的log也放上来了，在25epoch时精度收敛到了74.1% AO
[artrackv2_seq-artrackv2_seq_256_got.log](https://github.com/user-attachments/files/18037930/artrackv2_seq-artrackv2_seq_256_got.log)

**Comment by Feng0o7** [comment]
> 我把二阶段单卡的log也放上来了，在25epoch时精度收敛到了74.1% AO [artrackv2_seq-artrackv2_seq_256_got.log](https://github.com/user-attachments/files/18037930/artrackv2_seq-artrackv2_seq_256_got.log) 如您还有新的问题欢迎你随时提问。

好的，非常感谢了！！
