### ISSUE TITLE
请问有可以直接复现 实现跟踪效果的完整版代码吗

### ISSUE THREAD

**Issue by MiNi650** [MIV-XJTU/ARTrack#95]
我没有显卡来进行训练，但是我想看一下效果  /(ㄒoㄒ)/~~

**Comment by AlexDotHam** [comment]
这可能需要你自行写一部分代码，如OSTrack中的这个文件：
[video_demo.py](https://github.com/botaoye/OSTrack/blob/main/tracking/video_demo.py)
由于我们使用了近似的推理框架，因此可以通过调整一些参数直接使用，希望对您有用。

**Comment by MiNi650** [comment]
error: the following arguments are required: tracker_name, tracker_param, videofile 跟踪算法和参数文件该怎么填呢

**Comment by AlexDotHam** [comment]
您可以参考：https://github.com/MCG-NJU/MixFormer/blob/main/tracking/run_video_demo.sh


来设置对应的参数，您也可以直接用他的shell文件，只需要把tracker_name和tracker_params替换成我们的artrackv2_seq 和对应的config即可


 

-----原始邮件-----
发件人:MiNi650 ***@***.***>
发送时间:2024-12-04 18:57:20 (星期三)
收件人: MIV-XJTU/ARTrack ***@***.***>
抄送: "Yifan Bai" ***@***.***>, Comment ***@***.***>
主题: Re: [MIV-XJTU/ARTrack] 请问有可以直接复现 实现跟踪效果的完整版代码吗 (Issue #95)






error: the following arguments are required: tracker_name, tracker_param, videofile 跟踪算法和参数文件该怎么填呢

**Comment by MiNi650** [comment]
<img width="954" alt="a25e0c54509d85d7ae53df88356f0c0" src="https://github.com/user-attachments/assets/befc4d7d-ad15-4bee-afce-85e9c2dd50d0">
我在debug的时候发现config.py 168行那个filename是您的yaml文件地址'/home/baiyifan/code/AR2_github/ARTrack-main/experiments/artrackv2_seq/artrackv2_seq_256_full.yaml'
，我尝试了许多方法都无法修改到我这里 请问我该如何解决问题才能继续运行demo呢

**Comment by AlexDotHam** [comment]
[local.py](https://github.com/MIV-XJTU/ARTrack/blob/main/lib/test/evaluation/local.py)
这个文件包含了所有的路径，您可以修改其中的prj_dir
