### ISSUE TITLE
二阶段训练应该加载一阶段的哪个epoch？

### ISSUE THREAD

**Issue by jiaxianxin** [MIV-XJTU/ARTrack#96]
作者，你好！非常感谢作者这项出色的工作，请问一下，二阶段训练应该加载一阶段训练好的的哪个epoch？代码里一阶段是训练300epoch，二阶段训练40epoch。意思是，二阶段用一阶段的第300个epoch，测试用二阶段的第40个epoch吗？期待作者的回答，感谢！

**Comment by AlexDotHam** [comment]
是的，您的理解是正确的
