### ISSUE TITLE
Alternative Download Links for ARTrackV2 Checkpoints

### ISSUE THREAD

**Issue by alongigi** [MIV-XJTU/ARTrack#98]
Hi @AlexDotHam,

Congratulations on the excellent and impactful work on ARTrackV2!

I’m reaching out to kindly ask if alternative download links could be provided for the following ARTrackV2 checkpoints, as I’m unable to access files hosted on Baidu Pan:

Baidu Pan link:
https://pan.baidu.com/s/1bpdLdwO39kHD5iH06aGIzg?pwd=g06j#list/path=%2FARTrack-Checkpoints

File names:

ARTrackV2_large_384_got.pth.tar
ARTrackV2_base_256_got.pth.tar
ARTrackV2_base_256_full.pth.tar

If it’s possible to host these files on an alternative platform, I would greatly appreciate it.

Thank you in advance for your time and support!

Best regards,
Alon

**Comment by AlexDotHam** [comment]
You can get the checkpoints in README, where the table presents the performance of ARTrackV2 have the link to Google Drive.
  [ARTrackV2-B-256](https://drive.google.com/file/d/1tGaY5jQxZOTzJDWXgOgoHtBwc5l4NLQ2/view?usp=drive_link)       |     [ARTrackV2-B-256-GOT](https://drive.google.com/file/d/1RqsjHqTBsIN5ivD-C5tXDyhZlGZjJN88/view?usp=drive_link)     |     [ARTrackV2-L-384-GOT](https://drive.google.com/file/d/1KJ-TXFSn6K_OhchoRE29ePZbSm9sBHVS/view?usp=drive_link)     |

**Comment by alongigi** [comment]
Hi @AlexDotHam,

Thank you so much for the quick response and for providing the Google Drive links in the README. I was able to access the checkpoints successfully.

I’ll go ahead and close this issue. I really appreciate your time and support!

Best regards,
Alon
